name: tests

on: [push]

jobs:
  gn-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build the Docker Image
        run: docker build -t test-image -f Dockerfile .

      - name: Run Tests inside Docker Container
        run: docker run --rm test-image sh -c "chmod +x ./scripts/run_test.sh && ./scripts/run_test.sh Projects/NUCLEO-WB55RG/Examples/Blink_LED"