name: Test with Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build the Docker Image
        run: docker build -t my-test-image -f Dockerfile .
  
      - name: Run Tests inside Docker Container
        run: docker run --rm my-test-image ./scripts/run_test.sh

      - name: Run Tests
        run: ./scripts/run_test.sh Projects/NUCLEO-WB55RG/Examples/Blink_LED
